uploads = []
generated = []

[[outputs]]
id = "hJgtd78N5mqTQRXLnU9e7"
uri = "file://screenshots/mobile-home.jpg"
type = "image"
title = "1. Home - المستويات"

[[outputs]]
id = "S5y2wqa4u8faEqNTMXN3y"
uri = "file://artifacts/ola-arabic-mobile/builds/ola-arabic-mobile.aab"
type = "unspecified"
title = "Ola Arabic Android App Bundle (AAB) جاهز للرفع على Google Play"

[[outputs]]
id = "5pfsD7xA0ls5esiHNP4QZ"
uri = "file://screenshots/mobile-select-curriculum.jpg"
type = "image"
title = "2. Select Curriculum - اختيار المنهج"

[[outputs]]
id = "HfAFLKQb_iKKBl4wULi_y"
uri = "file://screenshots/mobile-grade-g1.jpg"
type = "image"
title = "3. Malaysian Stage 1 - المنهج الماليزي"

[[outputs]]
id = "-oXwKrIl_HOpdcPREOK-9"
uri = "file://screenshots/mobile-grade-uae-g1.jpg"
type = "image"
title = "4. UAE Stage 1 - المنهج الإماراتي"

[[outputs]]
id = "Kp5kS7WJURs5tE-8kxtvv"
uri = "file://screenshots/mobile-grade-indonesia-g1.jpg"
type = "image"
title = "5. Indonesian Stage 1 - المنهج الإندونيسي"

[[outputs]]
id = "4cicuGEB8ejFeiGsI1Dbk"
uri = "file://screenshots/mobile-grade-g2.jpg"
type = "image"
title = "6. Malaysian Stage 2 - المستوى الثاني"

[[outputs]]
id = "oD38Edmb9Cqxbf5vjJ1vc"
uri = "file://screenshots/mobile-lesson-g1u1l1.jpg"
type = "image"
title = "7. Lesson - درس من المنهج الماليزي"

[[outputs]]
id = "KuQLwnR3ghVWVOxvKqyJh"
uri = "file://screenshots/mobile-lesson-uae-g1u1l1.jpg"
type = "image"
title = "8. Lesson - درس من المنهج الإماراتي"

[[outputs]]
id = "eB70TUfc9zCwAHB_7I1ff"
uri = "file://screenshots/mobile-practice.jpg"
type = "image"
title = "9. Practice - التدريب"

[[outputs]]
id = "e2PatcXISIkhjCH4CPCVV"
uri = "file://screenshots/mobile-profile.jpg"
type = "image"
title = "10. Profile - الملف الشخصي"

[[outputs]]
id = "YDiUQusLNUl4Y95CJIkIf"
uri = "file://apk-preview/ola-arabic-preview.apk"
type = "unspecified"
title = "Ola Arabic Preview APK"
