import re, os
files = [f"artifacts/api-server/src/data/uae-grade{i}.ts" for i in range(1, 9)]

en_map = {
    "Getting to Know Each Other": "Introductions",
    "My First Words": "First Words",
    "My Little Body": "Body",
    "My Five Senses": "Senses",
    "My Healthy Food": "Healthy Food",
    "My Little World": "My World",
    "My Family and Me": "Family",
    "My Friends and Me": "Friends",
    "My Neighbours and Me": "Neighbours",
    "The Clock and the Date": "Clock and Date",
    "In the Music Room": "Music Room",
    "In the Yard": "Yard",
    "In the Bus": "Bus",
    "My Dearest Friends": "Best Friends",
    "Arts... Artists": "Arts",
    "Meeting and Farewell": "Meeting",
    "Family Gatherings": "Family",
    "No to Bullying": "No Bullying",
    "The Year of Tolerance": "Year of Tolerance",
    "My Foreign Friend": "Foreign Friend",
    "The Safety Generation": "Safety Generation",
    "Open-Minded": "Open-Minded",
    "Noise and Disorder": "Noise",
    "Long Live My Country": "My Country",
    "The Role Model": "Role Model",
    "Loyalty and Belonging": "Loyalty",
    "Volunteering is a Purpose": "Volunteering",
    "Advertising and Culture": "Advertising",
    "Food and Drink": "Food",
    "Coexistence and Tolerance": "Tolerance",
    "Science and Technology": "Science",
    "Energy Sources": "Energy",
    "Hope Probe": "Hope Probe",
    "Bullying and Tolerance": "Tolerance",
    "The Space": "Space",
    "The Health": "Health",
    "Human Rights": "Rights",
    "The Media": "Media",
    "The Shopping": "Shopping",
    "The Travel": "Travel",
    "The Environment": "Environment",
    "The Safety": "Safety",
    "The Emirati Identity": "Identity",
    "The Cultural Heritage": "Heritage",
    "The Future": "Future",
    "The Technology": "Technology",
    "The Communication": "Communication",
    "The Social Media": "Social Media",
    "The Volunteering": "Volunteering",
    "The Leadership": "Leadership",
    "The Innovation": "Innovation",
    "The Sustainability": "Sustainability",
    "The Tolerance": "Tolerance",
    "The Happiness": "Happiness",
    "The Positivity": "Positivity",
    "The Giving": "Giving",
    "The Ambition": "Ambition",
    "The Achievement": "Achievement",
    "The Sports": "Sports",
    "The Health": "Health",
    "The Nutrition": "Nutrition",
    "The Hygiene": "Hygiene",
    "The Sleep": "Sleep",
    "The Exercise": "Exercise",
    "The Doctor": "Doctor",
    "The Hospital": "Hospital",
    "The Emergency": "Emergency",
    "The Road Safety": "Road Safety",
    "The Fire Safety": "Fire Safety",
    "The Home Safety": "Home Safety",
    "The Water Safety": "Water Safety",
    "The Weather": "Weather",
    "The Seasons": "Seasons",
    "The Clothes": "Clothes",
    "The House": "House",
    "The Room": "Room",
    "The Furniture": "Furniture",
    "The Kitchen": "Kitchen",
    "The Food": "Food",
    "The Drinks": "Drinks",
    "The Fruits": "Fruits",
    "The Vegetables": "Vegetables",
    "The Breakfast": "Breakfast",
    "The Lunch": "Lunch",
    "The Dinner": "Dinner",
    "The Restaurant": "Restaurant",
    "The Market": "Market",
    "The Shop": "Shop",
    "The Money": "Money",
    "The Price": "Price",
    "The Payment": "Payment",
    "The Receipt": "Receipt",
    "The Discount": "Discount",
    "The Customer": "Customer",
    "The Seller": "Seller",
    "The Product": "Product",
    "The Quality": "Quality",
    "The Quantity": "Quantity",
    "The Measurement": "Measurement",
    "The Weight": "Weight",
    "The Length": "Length",
    "The Size": "Size",
    "The Color": "Color",
    "The Shape": "Shape",
    "The Number": "Number",
    "The Counting": "Counting",
    "The Math": "Math",
    "The Addition": "Addition",
    "The Subtraction": "Subtraction",
    "The Multiplication": "Multiplication",
    "The Division": "Division",
    "The Fraction": "Fraction",
    "The Decimal": "Decimal",
    "The Percentage": "Percentage",
    "The Time": "Time",
    "The Date": "Date",
    "The Calendar": "Calendar",
    "The Birthday": "Birthday",
    "The Holiday": "Holiday",
    "The Festival": "Festival",
    "The Celebration": "Celebration",
    "The Invitation": "Invitation",
    "The Gift": "Gift",
    "The Card": "Card",
    "The Decoration": "Decoration",
    "The Party": "Party",
    "The Game": "Game",
    "The Toy": "Toy",
    "The Hobby": "Hobby",
    "The Sport": "Sport",
    "The Team": "Team",
    "The Player": "Player",
    "The Coach": "Coach",
    "The Referee": "Referee",
    "The Winner": "Winner",
    "The Loser": "Loser",
    "The Competition": "Competition",
    "The Medal": "Medal",
    "The Trophy": "Trophy",
    "The Record": "Record",
    "The Music": "Music",
    "The Song": "Song",
    "The Instrument": "Instrument",
    "The Dance": "Dance",
    "The Art": "Art",
    "The Drawing": "Drawing",
    "The Painting": "Painting",
    "The Color": "Color",
    "The Sculpture": "Sculpture",
    "The Artist": "Artist",
    "The Museum": "Museum",
    "The Theater": "Theater",
    "The Cinema": "Cinema",
    "The Film": "Film",
    "The Book": "Book",
    "The Library": "Library",
    "The Reading": "Reading",
    "The Writing": "Writing",
    "The Story": "Story",
    "The Poem": "Poem",
    "The Author": "Author",
    "The Character": "Character",
    "The Plot": "Plot",
    "The Setting": "Setting",
    "The Ending": "Ending",
    "The Title": "Title",
    "The Page": "Page",
    "The Chapter": "Chapter",
    "The Lesson": "Lesson",
    "The Subject": "Subject",
    "The Homework": "Homework",
    "The Exam": "Exam",
    "The Test": "Test",
    "The Question": "Question",
    "The Answer": "Answer",
    "The Correct": "Correct",
    "The Wrong": "Wrong",
    "The Score": "Score",
    "The Grade": "Grade",
    "The Mark": "Mark",
    "The Result": "Result",
    "The Certificate": "Certificate",
    "The Diploma": "Diploma",
    "The Degree": "Degree",
    "The University": "University",
    "The College": "College",
    "The School": "School",
    "The Classroom": "Classroom",
    "The Teacher": "Teacher",
    "The Student": "Student",
    "The Classmate": "Classmate",
    "The Friend": "Friend",
    "The Principal": "Principal",
    "The Staff": "Staff",
    "The Worker": "Worker",
    "The Cleaner": "Cleaner",
    "The Driver": "Driver",
    "The Guard": "Guard",
    "The Nurse": "Nurse",
    "The Doctor": "Doctor",
    "The Patient": "Patient",
    "The Medicine": "Medicine",
    "The Pharmacy": "Pharmacy",
    "The Hospital": "Hospital",
    "The Clinic": "Clinic",
    "The Ambulance": "Ambulance",
    "The Police": "Police",
    "The Firefighter": "Firefighter",
    "The Soldier": "Soldier",
    "The Engineer": "Engineer",
    "The Architect": "Architect",
    "The Builder": "Builder",
    "The Carpenter": "Carpenter",
    "The Electrician": "Electrician",
    "The Plumber": "Plumber",
    "The Mechanic": "Mechanic",
    "The Farmer": "Farmer",
    "The Fisherman": "Fisherman",
    "The Chef": "Chef",
    "The Waiter": "Waiter",
    "The Cashier": "Cashier",
    "The Shopkeeper": "Shopkeeper",
    "The Tailor": "Tailor",
    "The Barber": "Barber",
    "The Hairdresser": "Hairdresser",
    "The Photographer": "Photographer",
    "The Journalist": "Journalist",
    "The Lawyer": "Lawyer",
    "The Judge": "Judge",
    "The Politician": "Politician",
    "The Scientist": "Scientist",
    "The Researcher": "Researcher",
    "The Explorer": "Explorer",
    "The Astronaut": "Astronaut",
    "The Pilot": "Pilot",
    "The Captain": "Captain",
    "The Sailor": "Sailor",
    "The Passenger": "Passenger",
    "The Tourist": "Tourist",
    "The Guide": "Guide",
    "The Map": "Map",
    "The Direction": "Direction",
    "The Location": "Location",
    "The Address": "Address",
    "The City": "City",
    "The Village": "Village",
    "The Country": "Country",
    "The Nationality": "Nationality",
    "The Language": "Language",
    "The Culture": "Culture",
    "The Tradition": "Tradition",
    "The Custom": "Custom",
    "The Religion": "Religion",
    "The Mosque": "Mosque",
    "The Prayer": "Prayer",
    "The Quran": "Quran",
    "The Hadith": "Hadith",
    "The Prophet": "Prophet",
    "The Messenger": "Messenger",
    "The Angel": "Angel",
    "The Heaven": "Heaven",
    "The Hell": "Hell",
    "The Judgement": "Judgement",
    "The Faith": "Faith",
    "The Belief": "Belief",
    "The Worship": "Worship",
    "The Fasting": "Fasting",
    "The Charity": "Charity",
    "The Pilgrimage": "Pilgrimage",
    "The Eid": "Eid",
    "The Ramadan": "Ramadan",
    "The Hajj": "Hajj",
    "The Umrah": "Umrah",
    "The Sacrifice": "Sacrifice",
    "The Festival": "Festival",
    "The Holiday": "Holiday",
    "The Vacation": "Vacation",
    "The Journey": "Journey",
    "The Trip": "Trip",
    "The Adventure": "Adventure",
    "The Discovery": "Discovery",
    "The Invention": "Invention",
    "The Experiment": "Experiment",
    "The Laboratory": "Laboratory",
    "The Microscope": "Microscope",
    "The Telescope": "Telescope",
    "The Computer": "Computer",
    "The Internet": "Internet",
    "The Website": "Website",
    "The Email": "Email",
    "The Phone": "Phone",
    "The Message": "Message",
    "The Application": "Application",
    "The Program": "Program",
    "The Code": "Code",
    "The Robot": "Robot",
    "The Machine": "Machine",
    "The Engine": "Engine",
    "The Car": "Car",
    "The Bicycle": "Bicycle",
    "The Bus": "Bus",
    "The Train": "Train",
    "The Plane": "Plane",
    "The Ship": "Ship",
    "The Boat": "Boat",
    "The Traffic": "Traffic",
    "The Road": "Road",
    "The Street": "Street",
    "The Bridge": "Bridge",
    "The Tunnel": "Tunnel",
    "The Building": "Building",
    "The Skyscraper": "Skyscraper",
    "The Apartment": "Apartment",
    "The Villa": "Villa",
    "The Tent": "Tent",
    "The Garden": "Garden",
    "The Park": "Park",
    "The Zoo": "Zoo",
    "The Aquarium": "Aquarium",
    "The Farm": "Farm",
    "The Forest": "Forest",
    "The Jungle": "Jungle",
    "The Desert": "Desert",
    "The Mountain": "Mountain",
    "The Valley": "Valley",
    "The River": "River",
    "The Lake": "Lake",
    "The Sea": "Sea",
    "The Ocean": "Ocean",
    "The Beach": "Beach",
    "The Island": "Island",
    "The Peninsula": "Peninsula",
    "The Coast": "Coast",
    "The Wave": "Wave",
    "The Sand": "Sand",
    "The Rock": "Rock",
    "The Soil": "Soil",
    "The Mud": "Mud",
    "The Clay": "Clay",
    "The Gold": "Gold",
    "The Silver": "Silver",
    "The Copper": "Copper",
    "The Iron": "Iron",
    "The Steel": "Steel",
    "The Glass": "Glass",
    "The Wood": "Wood",
    "The Paper": "Paper",
    "The Plastic": "Plastic",
    "The Metal": "Metal",
    "The Cotton": "Cotton",
    "The Wool": "Wool",
    "The Silk": "Silk",
    "The Leather": "Leather",
    "The Rubber": "Rubber",
    "The Stone": "Stone",
    "The Brick": "Brick",
    "The Cement": "Cement",
    "The Paint": "Paint",
    "The Brush": "Brush",
    "The Pen": "Pen",
    "The Pencil": "Pencil",
    "The Eraser": "Eraser",
    "The Ruler": "Ruler",
    "The Scissors": "Scissors",
    "The Glue": "Glue",
    "The Tape": "Tape",
    "The Stapler": "Stapler",
    "The Hole Punch": "Hole Punch",
    "The Marker": "Marker",
    "The Crayon": "Crayon",
    "The Paintbrush": "Paintbrush",
    "The Palette": "Palette",
    "The Canvas": "Canvas",
    "The Easel": "Easel",
    "The Sketchbook": "Sketchbook",
    "The Notebook": "Notebook",
    "The Textbook": "Textbook",
    "The Workbook": "Workbook",
    "The Dictionary": "Dictionary",
    "The Encyclopedia": "Encyclopedia",
    "The Atlas": "Atlas",
    "The Globe": "Globe",
    "The Map": "Map",
    "The Compass": "Compass",
    "The Clock": "Clock",
    "The Watch": "Watch",
    "The Calendar": "Calendar",
    "The Timer": "Timer",
    "The Alarm": "Alarm",
    "The Bell": "Bell",
    "The Whistle": "Whistle",
    "The Horn": "Horn",
    "The Drum": "Drum",
    "The Flute": "Flute",
    "The Guitar": "Guitar",
    "The Piano": "Piano",
    "The Violin": "Violin",
    "The Trumpet": "Trumpet",
    "The Saxophone": "Saxophone",
    "The Microphone": "Microphone",
    "The Speaker": "Speaker",
    "The Headphones": "Headphones",
    "The Camera": "Camera",
    "The Video": "Video",
    "The Television": "Television",
    "The Radio": "Radio",
    "The Newspaper": "Newspaper",
    "The Magazine": "Magazine",
    "The Letter": "Letter",
    "The Envelope": "Envelope",
    "The Stamp": "Stamp",
    "The Postcard": "Postcard",
    "The Package": "Package",
    "The Box": "Box",
    "The Bag": "Bag",
    "The Backpack": "Backpack",
    "The Suitcase": "Suitcase",
    "The Luggage": "Luggage",
    "The Wallet": "Wallet",
    "The Purse": "Purse",
    "The Umbrella": "Umbrella",
    "The Key": "Key",
    "The Lock": "Lock",
    "The Door": "Door",
    "The Window": "Window",
    "The Wall": "Wall",
    "The Floor": "Floor",
    "The Ceiling": "Ceiling",
    "The Roof": "Roof",
    "The Stairs": "Stairs",
    "The Elevator": "Elevator",
    "The Escalator": "Escalator",
    "The Doorbell": "Doorbell",
    "The Doorknob": "Doorknob",
    "The Handle": "Handle",
    "The Switch": "Switch",
    "The Plug": "Plug",
    "The Socket": "Socket",
    "The Wire": "Wire",
    "The Cable": "Cable",
    "The Charger": "Charger",
    "The Battery": "Battery",
    "The Bulb": "Bulb",
    "The Lamp": "Lamp",
    "The Light": "Light",
    "The Fan": "Fan",
    "The Air Conditioner": "Air Conditioner",
    "The Heater": "Heater",
    "The Refrigerator": "Refrigerator",
    "The Freezer": "Freezer",
    "The Oven": "Oven",
    "The Stove": "Stove",
    "The Microwave": "Microwave",
    "The Blender": "Blender",
    "The Mixer": "Mixer",
    "The Toaster": "Toaster",
    "The Kettle": "Kettle",
    "The Coffee Maker": "Coffee Maker",
    "The Dishwasher": "Dishwasher",
    "The Washing Machine": "Washing Machine",
    "The Dryer": "Dryer",
    "The Vacuum Cleaner": "Vacuum Cleaner",
    "The Broom": "Broom",
    "The Mop": "Mop",
    "The Bucket": "Bucket",
    "The Dustpan": "Dustpan",
    "The Trash Can": "Trash Can",
    "The Recycling Bin": "Recycling Bin",
    "The Soap": "Soap",
    "The Shampoo": "Shampoo",
    "The Toothpaste": "Toothpaste",
    "The Toothbrush": "Toothbrush",
    "The Towel": "Towel",
    "The Tissue": "Tissue",
    "The Napkin": "Napkin",
    "The Mirror": "Mirror",
    "The Comb": "Comb",
    "The Brush": "Brush",
    "The Razor": "Razor",
    "The Perfume": "Perfume",
    "The Deodorant": "Deodorant",
    "The Lotion": "Lotion",
    "The Cream": "Cream",
    "The Powder": "Powder",
    "The Lipstick": "Lipstick",
    "The Makeup": "Makeup",
    "The Jewelry": "Jewelry",
    "The Ring": "Ring",
    "The Necklace": "Necklace",
    "The Bracelet": "Bracelet",
    "The Earring": "Earring",
    "The Crown": "Crown",
    "The Glasses": "Glasses",
    "The Sunglasses": "Sunglasses",
    "The Contact Lenses": "Contact Lenses",
    "The Hat": "Hat",
    "The Cap": "Cap",
    "The Helmet": "Helmet",
    "The Scarf": "Scarf",
    "The Gloves": "Gloves",
    "The Socks": "Socks",
    "The Shoes": "Shoes",
    "The Slippers": "Slippers",
    "The Boots": "Boots",
    "The Sandals": "Sandals",
    "The Belt": "Belt",
    "The Tie": "Tie",
    "The Bow Tie": "Bow Tie",
    "The Shirt": "Shirt",
    "The T-Shirt": "T-Shirt",
    "The Blouse": "Blouse",
    "The Sweater": "Sweater",
    "The Jacket": "Jacket",
    "The Coat": "Coat",
    "The Raincoat": "Raincoat",
    "The Pants": "Pants",
    "The Shorts": "Shorts",
    "The Skirt": "Skirt",
    "The Dress": "Dress",
    "The Suit": "Suit",
    "The Uniform": "Uniform",
    "The Apron": "Apron",
    "The Pajamas": "Pajamas",
    "The Robe": "Robe",
    "The Towel": "Towel",
    "The Blanket": "Blanket",
    "The Pillow": "Pillow",
    "The Sheet": "Sheet",
    "The Mattress": "Mattress",
    "The Bed": "Bed",
    "The Bunk Bed": "Bunk Bed",
    "The Crib": "Crib",
    "The Sofa": "Sofa",
    "The Couch": "Couch",
    "The Armchair": "Armchair",
    "The Recliner": "Recliner",
    "The Ottoman": "Ottoman",
    "The Coffee Table": "Coffee Table",
    "The Dining Table": "Dining Table",
    "The Chair": "Chair",
    "The Bench": "Bench",
    "The Stool": "Stool",
    "The Desk": "Desk",
    "The Bookshelf": "Bookshelf",
    "The Wardrobe": "Wardrobe",
    "The Closet": "Closet",
    "The Drawer": "Drawer",
    "The Cabinet": "Cabinet",
    "The Shelf": "Shelf",
    "The Rack": "Rack",
    "The Hanger": "Hanger",
    "The Laundry Basket": "Laundry Basket",
    "The Ironing Board": "Ironing Board",
    "The Iron": "Iron",
    "The Sewing Machine": "Sewing Machine",
    "The Thread": "Thread",
    "The Needle": "Needle",
    "The Button": "Button",
    "The Zipper": "Zipper",
    "The Pocket": "Pocket",
    "The Collar": "Collar",
    "The Sleeve": "Sleeve",
    "The Cuff": "Cuff",
    "The Hem": "Hem",
    "The Seam": "Seam",
    "The Fabric": "Fabric",
    "The Pattern": "Pattern",
    "The Design": "Design",
    "The Style": "Style",
    "The Fashion": "Fashion",
    "The Trend": "Trend",
    "The Brand": "Brand",
    "The Logo": "Logo",
    "The Label": "Label",
    "The Tag": "Tag",
    "The Price Tag": "Price Tag",
    "The Barcode": "Barcode",
    "The QR Code": "QR Code",
    "The Receipt": "Receipt",
    "The Invoice": "Invoice",
    "The Bill": "Bill",
    "The Coin": "Coin",
    "The Banknote": "Banknote",
    "The Credit Card": "Credit Card",
    "The Debit Card": "Debit Card",
    "The Check": "Check",
    "The Bank": "Bank",
    "The Account": "Account",
    "The ATM": "ATM",
    "The Teller": "Teller",
    "The Loan": "Loan",
    "The Interest": "Interest",
    "The Debt": "Debt",
    "The Profit": "Profit",
    "The Loss": "Loss",
    "The Investment": "Investment",
    "The Stock": "Stock",
    "The Share": "Share",
    "The Market": "Market",
    "The Economy": "Economy",
    "The Business": "Business",
    "The Company": "Company",
    "The Office": "Office",
    "The Meeting": "Meeting",
    "The Conference": "Conference",
    "The Presentation": "Presentation",
    "The Project": "Project",
    "The Report": "Report",
    "The Document": "Document",
    "The File": "File",
    "The Folder": "Folder",
    "The Binder": "Binder",
    "The Clipboard": "Clipboard",
    "The Staple": "Staple",
    "The Paperclip": "Paperclip",
    "The Rubber Band": "Rubber Band",
    "The Pushpin": "Pushpin",
    "The Thumbtack": "Thumbtack",
    "The Label Maker": "Label Maker",
    "The Laminator": "Laminator",
    "The Shredder": "Shredder",
    "The Printer": "Printer",
    "The Scanner": "Scanner",
    "The Copier": "Copier",
    "The Fax Machine": "Fax Machine",
    "The Projector": "Projector",
    "The Screen": "Screen",
    "The Whiteboard": "Whiteboard",
    "The Blackboard": "Blackboard",
    "The Chalk": "Chalk",
    "The Duster": "Duster",
    "The Sponge": "Sponge",
    "The Eraser": "Eraser",
    "The Sharpener": "Sharpener",
    "The Highlighter": "Highlighter",
    "The Ballpoint Pen": "Ballpoint Pen",
    "The Fountain Pen": "Fountain Pen",
    "The Gel Pen": "Gel Pen",
    "The Marker Pen": "Marker Pen",
    "The Permanent Marker": "Permanent Marker",
    "The Dry Erase Marker": "Dry Erase Marker",
    "The Flip Chart": "Flip Chart",
    "The Easel Pad": "Easel Pad",
    "The Sticky Note": "Sticky Note",
    "The Memo Pad": "Memo Pad",
    "The Notepad": "Notepad",
    "The Diary": "Diary",
    "The Journal": "Journal",
    "The Planner": "Planner",
    "The Agenda": "Agenda",
    "The Schedule": "Schedule",
    "The Timetable": "Timetable",
    "The Routine": "Routine",
    "The Habit": "Habit",
    "The Goal": "Goal",
    "The Target": "Target",
    "The Plan": "Plan",
    "The Strategy": "Strategy",
    "The Tactic": "Tactic",
    "The Mission": "Mission",
    "The Vision": "Vision",
    "The Value": "Value",
    "The Principle": "Principle",
    "The Rule": "Rule",
    "The Law": "Law",
    "The Regulation": "Regulation",
    "The Policy": "Policy",
    "The Procedure": "Procedure",
    "The Process": "Process",
    "The System": "System",
    "The Method": "Method",
    "The Technique": "Technique",
    "The Approach": "Approach",
    "The Style": "Style",
    "The Format": "Format",
    "The Template": "Template",
    "The Layout": "Layout",
    "The Structure": "Structure",
    "The Framework": "Framework",
    "The Model": "Model",
    "The Pattern": "Pattern",
    "The Example": "Example",
    "The Sample": "Sample",
    "The Instance": "Instance",
    "The Case": "Case",
    "The Study": "Study",
    "The Research": "Research",
    "The Analysis": "Analysis",
    "The Evaluation": "Evaluation",
    "The Assessment": "Assessment",
    "The Measurement": "Measurement",
    "The Observation": "Observation",
    "The Experiment": "Experiment",
    "The Test": "Test",
    "The Quiz": "Quiz",
    "The Survey": "Survey",
    "The Interview": "Interview",
    "The Discussion": "Discussion",
    "The Debate": "Debate",
    "The Argument": "Argument",
    "The Negotiation": "Negotiation",
    "The Agreement": "Agreement",
    "The Contract": "Contract",
    "The Deal": "Deal",
    "The Promise": "Promise",
    "The Commitment": "Commitment",
    "The Responsibility": "Responsibility",
    "The Duty": "Duty",
    "The Task": "Task",
    "The Job": "Job",
    "The Work": "Work",
    "The Career": "Career",
    "The Profession": "Profession",
    "The Occupation": "Occupation",
    "The Role": "Role",
    "The Position": "Position",
    "The Title": "Title",
    "The Rank": "Rank",
    "The Status": "Status",
    "The Level": "Level",
    "The Stage": "Stage",
    "The Phase": "Phase",
    "The Step": "Step",
    "The Action": "Action",
    "The Activity": "Activity",
    "The Exercise": "Exercise",
    "The Practice": "Practice",
    "The Drill": "Drill",
    "The Training": "Training",
    "The Coaching": "Coaching",
    "The Lesson": "Lesson",
    "The Course": "Course",
    "The Workshop": "Workshop",
    "The Seminar": "Seminar",
    "The Webinar": "Webinar",
    "The Tutorial": "Tutorial",
    "The Lecture": "Lecture",
    "The Class": "Class",
    "The Session": "Session",
    "The Term": "Term",
    "The Semester": "Semester",
    "The Academic Year": "Year",
    "The Vacation": "Vacation",
    "The Break": "Break",
    "The Recess": "Recess",
    "The Bell": "Bell",
    "The Lunch Break": "Lunch Break",
    "The Assembly": "Assembly",
    "The Flag Ceremony": "Flag Ceremony",
    "The National Anthem": "Anthem",
    "The Pledge": "Pledge",
    "The Oath": "Oath",
    "The Motto": "Motto",
    "The Slogan": "Slogan",
    "The Symbol": "Symbol",
    "The Emblem": "Emblem",
    "The Flag": "Flag",
    "The Banner": "Banner",
    "The Poster": "Poster",
    "The Sign": "Sign",
    "The Notice": "Notice",
    "The Announcement": "Announcement",
    "The Message": "Message",
    "The News": "News",
    "The Information": "Info",
    "The Knowledge": "Knowledge",
    "The Wisdom": "Wisdom",
    "The Truth": "Truth",
    "The Lie": "Lie",
    "The Fact": "Fact",
    "The Opinion": "Opinion",
    "The Idea": "Idea",
    "The Thought": "Thought",
    "The Mind": "Mind",
    "The Brain": "Brain",
    "The Heart": "Heart",
    "The Soul": "Soul",
    "The Spirit": "Spirit",
    "The Body": "Body",
    "The Health": "Health",
    "The Fitness": "Fitness",
    "The Wellness": "Wellness",
    "The Energy": "Energy",
    "The Strength": "Strength",
    "The Power": "Power",
    "The Force": "Force",
    "The Speed": "Speed",
    "The Velocity": "Velocity",
    "The Acceleration": "Acceleration",
    "The Motion": "Motion",
    "The Movement": "Movement",
    "The Action": "Action",
    "The Reaction": "Reaction",
    "The Balance": "Balance",
    "The Stability": "Stability",
    "The Coordination": "Coordination",
    "The Flexibility": "Flexibility",
    "The Endurance": "Endurance",
    "The Stamina": "Stamina",
    "The Agility": "Agility",
    "The Skill": "Skill",
    "The Ability": "Ability",
    "The Talent": "Talent",
    "The Gift": "Gift",
    "The Potential": "Potential",
    "The Capacity": "Capacity",
    "The Capability": "Capability",
    "The Competence": "Competence",
    "The Performance": "Performance",
    "The Achievement": "Achievement",
    "The Success": "Success",
    "The Failure": "Failure",
    "The Victory": "Victory",
    "The Defeat": "Defeat",
    "The Win": "Win",
    "The Loss": "Loss",
    "The Draw": "Draw",
    "The Tie": "Tie",
    "The Score": "Score",
    "The Point": "Point",
    "The Goal": "Goal",
    "The Aim": "Aim",
    "The Objective": "Objective",
    "The Purpose": "Purpose",
    "The Reason": "Reason",
    "The Cause": "Cause",
    "The Effect": "Effect",
    "The Result": "Result",
    "The Consequence": "Consequence",
    "The Impact": "Impact",
    "The Influence": "Influence",
    "The Benefit": "Benefit",
    "The Advantage": "Advantage",
    "The Disadvantage": "Disadvantage",
    "The Drawback": "Drawback",
    "The Risk": "Risk",
    "The Danger": "Danger",
    "The Threat": "Threat",
    "The Challenge": "Challenge",
    "The Difficulty": "Difficulty",
    "The Problem": "Problem",
    "The Issue": "Issue",
    "The Matter": "Matter",
    "The Topic": "Topic",
    "The Theme": "Theme",
    "The Subject": "Subject",
    "The Content": "Content",
    "The Context": "Context",
    "The Background": "Background",
    "The Setting": "Setting",
    "The Scene": "Scene",
    "The Environment": "Environment",
    "The Atmosphere": "Atmosphere",
    "The Mood": "Mood",
    "The Tone": "Tone",
    "The Style": "Style",
    "The Voice": "Voice",
    "The Sound": "Sound",
    "The Noise": "Noise",
    "The Music": "Music",
    "The Silence": "Silence",
    "The Rhythm": "Rhythm",
    "The Beat": "Beat",
    "The Melody": "Melody",
    "The Harmony": "Harmony",
    "The Lyrics": "Lyrics",
    "The Chorus": "Chorus",
    "The Verse": "Verse",
    "The Bridge": "Bridge",
    "The Intro": "Intro",
    "The Outro": "Outro",
    "The Solo": "Solo",
    "The Duet": "Duet",
    "The Trio": "Trio",
    "The Quartet": "Quartet",
    "The Band": "Band",
    "The Orchestra": "Orchestra",
    "The Choir": "Choir",
    "The Conductor": "Conductor",
    "The Composer": "Composer",
    "The Musician": "Musician",
    "The Singer": "Singer",
    "The Dancer": "Dancer",
    "The Actor": "Actor",
    "The Actress": "Actress",
    "The Director": "Director",
    "The Producer": "Producer",
    "The Screenwriter": "Screenwriter",
    "The Playwright": "Playwright",
    "The Audience": "Audience",
    "The Spectator": "Spectator",
    "The Viewer": "Viewer",
    "The Listener": "Listener",
    "The Reader": "Reader",
    "The Writer": "Writer",
    "The Author": "Author",
    "The Poet": "Poet",
    "The Novelist": "Novelist",
    "The Journalist": "Journalist",
    "The Reporter": "Reporter",
    "The Correspondent": "Correspondent",
    "The Editor": "Editor",
    "The Publisher": "Publisher",
    "The Translator": "Translator",
    "The Interpreter": "Interpreter",
    "The Linguist": "Linguist",
    "The Philologist": "Philologist",
    "The Grammarian": "Grammarian",
    "The Teacher": "Teacher",
    "The Instructor": "Instructor",
    "The Trainer": "Trainer",
    "The Tutor": "Tutor",
    "The Mentor": "Mentor",
    "The Coach": "Coach",
    "The Professor": "Professor",
    "The Lecturer": "Lecturer",
    "The Educator": "Educator",
    "The Pedagogue": "Pedagogue",
    "The Principal": "Principal",
    "The Headmaster": "Headmaster",
    "The Headmistress": "Headmistress",
    "The Dean": "Dean",
    "The Chancellor": "Chancellor",
    "The President": "President",
    "The Vice President": "Vice President",
    "The Manager": "Manager",
    "The Director": "Director",
    "The Supervisor": "Supervisor",
    "The Coordinator": "Coordinator",
    "The Administrator": "Administrator",
    "The Secretary": "Secretary",
    "The Assistant": "Assistant",
    "The Receptionist": "Receptionist",
    "The Operator": "Operator",
    "The Technician": "Technician",
    "The Specialist": "Specialist",
    "The Expert": "Expert",
    "The Consultant": "Consultant",
    "The Advisor": "Advisor",
    "The Counselor": "Counselor",
    "The Therapist": "Therapist",
    "The Psychologist": "Psychologist",
    "The Psychiatrist": "Psychiatrist",
    "The Social Worker": "Social Worker",
    "The Volunteer": "Volunteer",
    "The Helper": "Helper",
    "The Assistant": "Assistant",
    "The Intern": "Intern",
    "The Apprentice": "Apprentice",
    "The Trainee": "Trainee",
    "The Beginner": "Beginner",
    "The Novice": "Novice",
    "The Amateur": "Amateur",
    "The Professional": "Professional",
    "The Expert": "Expert",
    "The Master": "Master",
    "The Genius": "Genius",
    "The Talent": "Talent",
    "The Star": "Star",
    "The Celebrity": "Celebrity",
    "The Hero": "Hero",
    "The Heroine": "Heroine",
    "The Leader": "Leader",
    "The Follower": "Follower",
    "The Member": "Member",
    "The Participant": "Participant",
    "The Member": "Member",
    "The Citizen": "Citizen",
    "The Resident": "Resident",
    "The Visitor": "Visitor",
    "The Guest": "Guest",
    "The Host": "Host",
    "The Hostess": "Hostess",
    "The Neighbor": "Neighbor",
    "The Stranger": "Stranger",
    "The Foreigner": "Foreigner",
    "The Tourist": "Tourist",
    "The Traveler": "Traveler",
    "The Passenger": "Passenger",
    "The Commuter": "Commuter",
    "The Driver": "Driver",
    "The Pedestrian": "Pedestrian",
    "The Cyclist": "Cyclist",
    "The Motorcyclist": "Motorcyclist",
    "The Passenger": "Passenger",
    "The Customer": "Customer",
    "The Client": "Client",
    "The Consumer": "Consumer",
    "The Buyer": "Buyer",
    "The Seller": "Seller",
    "The Vendor": "Vendor",
    "The Merchant": "Merchant",
    "The Trader": "Trader",
    "The Businessman": "Businessman",
    "The Businesswoman": "Businesswoman",
    "The Entrepreneur": "Entrepreneur",
    "The Founder": "Founder",
    "The Owner": "Owner",
    "The Partner": "Partner",
    "The Shareholder": "Shareholder",
    "The Investor": "Investor",
    "The Sponsor": "Sponsor",
    "The Donor": "Donor",
    "The Benefactor": "Benefactor",
    "The Beneficiary": "Beneficiary",
    "The Recipient": "Recipient",
    "The Volunteer": "Volunteer",
    "The Member": "Member",
    "The Supporter": "Supporter",
    "The Fan": "Fan",
    "The Follower": "Follower",
    "The Subscriber": "Subscriber",
    "The Member": "Member",
    "The User": "User",
    "The Member": "Member",
    "The Account": "Account",
    "The Profile": "Profile",
    "The Avatar": "Avatar",
    "The Username": "Username",
    "The Password": "Password",
    "The Email": "Email",
    "The Phone Number": "Phone Number",
    "The Address": "Address",
    "The Contact": "Contact",
    "The Message": "Message",
    "The Notification": "Notification",
    "The Alert": "Alert",
    "The Reminder": "Reminder",
    "The Invitation": "Invitation",
    "The Request": "Request",
    "The Application": "Application",
    "The Form": "Form",
    "The Registration": "Registration",
    "The Login": "Login",
    "The Logout": "Logout",
    "The Password Reset": "Password Reset",
    "The Verification": "Verification",
    "The Confirmation": "Confirmation",
    "The Approval": "Approval",
    "The Rejection": "Rejection",
    "The Cancellation": "Cancellation",
    "The Refund": "Refund",
    "The Return": "Return",
    "The Exchange": "Exchange",
    "The Delivery": "Delivery",
    "The Shipping": "Shipping",
    "The Tracking": "Tracking",
    "The Order": "Order",
    "The Purchase": "Purchase",
    "The Sale": "Sale",
    "The Payment": "Payment",
    "The Transaction": "Transaction",
    "The Balance": "Balance",
    "The Deposit": "Deposit",
    "The Withdrawal": "Withdrawal",
    "The Transfer": "Transfer",
    "The Remittance": "Remittance",
    "The Currency": "Currency",
    "The Exchange Rate": "Exchange Rate",
    "The Fee": "Fee",
    "The Commission": "Commission",
    "The Tax": "Tax",
    "The Tip": "Tip",
    "The Discount": "Discount",
    "The Voucher": "Voucher",
    "The Coupon": "Coupon",
    "The Gift Card": "Gift Card",
    "The Loyalty Card": "Loyalty Card",
    "The Membership Card": "Membership Card",
    "The ID Card": "ID Card",
    "The Passport": "Passport",
    "The Visa": "Visa",
    "The Residence Permit": "Residence Permit",
    "The Driver's License": "License",
    "The Identity Card": "ID Card",
    "The Birth Certificate": "Birth Certificate",
    "The Marriage Certificate": "Marriage Certificate",
    "The Death Certificate": "Death Certificate",
    "The Diploma": "Diploma",
    "The Degree Certificate": "Degree Certificate",
    "The Transcript": "Transcript",
    "The Certificate": "Certificate",
    "The License": "License",
    "The Permit": "Permit",
    "The Authorization": "Authorization",
    "The Approval": "Approval",
    "The Clearance": "Clearance",
    "The Release": "Release",
    "The Waiver": "Waiver",
    "The Consent": "Consent",
    "The Permission": "Permission",
    "The Request": "Request",
    "The Petition": "Petition",
    "The Application": "Application",
    "The Appeal": "Appeal",
    "The Complaint": "Complaint",
    "The Feedback": "Feedback",
    "The Review": "Review",
    "The Rating": "Rating",
    "The Comment": "Comment",
    "The Reply": "Reply",
    "The Response": "Response",
    "The Answer": "Answer",
    "The Solution": "Solution",
    "The Resolution": "Resolution",
    "The Decision": "Decision",
    "The Judgment": "Judgment",
    "The Verdict": "Verdict",
    "The Sentence": "Sentence",
    "The Punishment": "Punishment",
    "The Penalty": "Penalty",
    "The Fine": "Fine",
    "The Imprisonment": "Imprisonment",
    "The Probation": "Probation",
    "The Parole": "Parole",
    "The Pardon": "Pardon",
    "The Amnesty": "Amnesty",
    "The Justice": "Justice",
    "The Fairness": "Fairness",
    "The Equality": "Equality",
    "The Equity": "Equity",
    "The Rights": "Rights",
    "The Freedom": "Freedom",
    "The Liberty": "Liberty",
    "The Democracy": "Democracy",
    "The Republic": "Republic",
    "The Constitution": "Constitution",
    "The Government": "Government",
    "The Parliament": "Parliament",
    "The Congress": "Congress",
    "The Senate": "Senate",
    "The Council": "Council",
    "The Ministry": "Ministry",
    "The Department": "Department",
    "The Agency": "Agency",
    "The Bureau": "Bureau",
    "The Committee": "Committee",
    "The Commission": "Commission",
    "The Board": "Board",
    "The Court": "Court",
    "The Tribunal": "Tribunal",
    "The Judge": "Judge",
    "The Jury": "Jury",
    "The Lawyer": "Lawyer",
    "The Prosecutor": "Prosecutor",
    "The Defendant": "Defendant",
    "The Plaintiff": "Plaintiff",
    "The Witness": "Witness",
    "The Evidence": "Evidence",
    "The Proof": "Proof",
    "The Alibi": "Alibi",
    "The Testimony": "Testimony",
    "The Oath": "Oath",
    "The Sworn Statement": "Sworn Statement",
    "The Affidavit": "Affidavit",
    "The Subpoena": "Subpoena",
    "The Summons": "Summons",
    "The Warrant": "Warrant",
    "The Arrest": "Arrest",
    "The Custody": "Custody",
    "The Bail": "Bail",
    "The Bond": "Bond",
    "The Release": "Release",
    "The Freedom": "Freedom",
    "The Prison": "Prison",
    "The Jail": "Jail",
    "The Detention": "Detention",
    "The Rehabilitation": "Rehabilitation",
    "The Correction": "Correction",
    "The Reform": "Reform",
    "The Education": "Education",
    "The Training": "Training",
    "The Development": "Development",
    "The Growth": "Growth",
    "The Progress": "Progress",
    "The Advancement": "Advancement",
    "The Improvement": "Improvement",
    "The Enhancement": "Enhancement",
    "The Upgrade": "Upgrade",
    "The Update": "Update",
    "The Maintenance": "Maintenance",
    "The Repair": "Repair",
    "The Fix": "Fix",
    "The Patch": "Patch",
    "The Replacement": "Replacement",
    "The Installation": "Installation",
    "The Setup": "Setup",
    "The Configuration": "Configuration",
    "The Customization": "Customization",
    "The Personalization": "Personalization",
    "The Optimization": "Optimization",
    "The Tuning": "Tuning",
    "The Adjustment": "Adjustment",
    "The Calibration": "Calibration",
    "The Alignment": "Alignment",
    "The Balancing": "Balancing",
    "The Testing": "Testing",
    "The Debugging": "Debugging",
    "The Troubleshooting": "Troubleshooting",
    "The Diagnosis": "Diagnosis",
    "The Repair": "Repair",
    "The Restoration": "Restoration",
    "The Recovery": "Recovery",
    "The Backup": "Backup",
    "The Archiving": "Archiving",
    "The Storage": "Storage",
    "The Retrieval": "Retrieval",
    "The Access": "Access",
    "The Security": "Security",
    "The Protection": "Protection",
    "The Safety": "Safety",
    "The Privacy": "Privacy",
    "The Confidentiality": "Confidentiality",
    "The Encryption": "Encryption",
    "The Decryption": "Decryption",
    "The Authentication": "Authentication",
    "The Authorization": "Authorization",
    "The Permission": "Permission",
    "The Access Control": "Access Control",
    "The Firewall": "Firewall",
    "The Antivirus": "Antivirus",
    "The Malware": "Malware",
    "The Virus": "Virus",
    "The Worm": "Worm",
    "The Trojan": "Trojan",
    "The Ransomware": "Ransomware",
    "The Spyware": "Spyware",
    "The Adware": "Adware",
    "The Phishing": "Phishing",
    "The Scam": "Scam",
    "The Fraud": "Fraud",
    "The Hacking": "Hacking",
    "The Breach": "Breach",
    "The Leak": "Leak",
    "The Data": "Data",
    "The Database": "Database",
    "The Server": "Server",
    "The Cloud": "Cloud",
    "The Network": "Network",
    "The Connection": "Connection",
    "The Signal": "Signal",
    "The Wi-Fi": "Wi-Fi",
    "The Bluetooth": "Bluetooth",
    "The Ethernet": "Ethernet",
    "The Cable": "Cable",
    "The Fiber": "Fiber",
    "The Satellite": "Satellite",
    "The Tower": "Tower",
    "The Antenna": "Antenna",
    "The Router": "Router",
    "The Modem": "Modem",
    "The Switch": "Switch",
    "The Hub": "Hub",
    "The Bridge": "Bridge",
    "The Repeater": "Repeater",
    "The Extender": "Extender",
    "The Access Point": "Access Point",
    "The Hotspot": "Hotspot",
    "The Domain": "Domain",
    "The URL": "URL",
    "The Link": "Link",
    "The Hyperlink": "Hyperlink",
    "The Browser": "Browser",
    "The Search Engine": "Search Engine",
    "The Website": "Website",
    "The Webpage": "Webpage",
    "The Site": "Site",
    "The Portal": "Portal",
    "The Platform": "Platform",
    "The Service": "Service",
    "The Tool": "Tool",
    "The Utility": "Utility",
    "The Feature": "Feature",
    "The Function": "Function",
    "The Capability": "Capability",
    "The Option": "Option",
    "The Setting": "Setting",
    "The Preference": "Preference",
    "The Mode": "Mode",
    "The Status": "Status",
    "The Indicator": "Indicator",
    "The Icon": "Icon",
    "The Button": "Button",
    "The Menu": "Menu",
    "The Tab": "Tab",
    "The Window": "Window",
    "The Dialog": "Dialog",
    "The Popup": "Popup",
    "The Modal": "Modal",
    "The Sidebar": "Sidebar",
    "The Panel": "Panel",
    "The Dashboard": "Dashboard",
    "The Widget": "Widget",
    "The Card": "Card",
    "The List": "List",
    "The Grid": "Grid",
    "The Table": "Table",
    "The Chart": "Chart",
    "The Graph": "Graph",
    "The Diagram": "Diagram",
    "The Map": "Map",
    "The Timeline": "Timeline",
    "The Calendar": "Calendar",
    "The Clock": "Clock",
    "The Timer": "Timer",
    "The Counter": "Counter",
    "The Progress Bar": "Progress Bar",
    "The Spinner": "Spinner",
    "The Loader": "Loader",
    "The Skeleton": "Skeleton",
    "The Placeholder": "Placeholder",
    "The Empty State": "Empty State",
    "The Error State": "Error State",
    "The Success State": "Success State",
    "The Loading State": "Loading State",
    "The Offline State": "Offline State",
    "The Online State": "Online State",
    "The Active State": "Active State",
    "The Inactive State": "Inactive State",
    "The Hover State": "Hover State",
    "The Focus State": "Focus State",
    "The Disabled State": "Disabled State",
    "The Selected State": "Selected State",
    "The Checked State": "Checked State",
    "The Indeterminate State": "Indeterminate State",
    "The Default State": "Default State",
    "The Initial State": "Initial State",
    "The Final State": "Final State",
    "The Transition": "Transition",
    "The Animation": "Animation",
    "The Motion": "Motion",
    "The Effect": "Effect",
    "The Interaction": "Interaction",
    "The Gesture": "Gesture",
    "The Touch": "Touch",
    "The Click": "Click",
    "The Tap": "Tap",
    "The Swipe": "Swipe",
    "The Drag": "Drag",
    "The Drop": "Drop",
    "The Scroll": "Scroll",
    "The Pinch": "Pinch",
    "The Zoom": "Zoom",
    "The Rotate": "Rotate",
    "The Pan": "Pan",
    "The Long Press": "Long Press",
    "The Double Tap": "Double Tap",
    "The Right Click": "Right Click",
    "The Hover": "Hover",
    "The Focus": "Focus",
    "The Blur": "Blur",
    "The Key Press": "Key Press",
    "The Keyboard Shortcut": "Shortcut",
    "The Hotkey": "Hotkey",
    "The Command": "Command",
    "The Shortcut": "Shortcut",
    "The Macro": "Macro",
    "The Script": "Script",
    "The Automation": "Automation",
    "The Bot": "Bot",
    "The Assistant": "Assistant",
    "The AI": "AI",
    "The Agent": "Agent",
    "The Model": "Model",
    "The Algorithm": "Algorithm",
    "The Data Set": "Data Set",
    "The Training Data": "Training Data",
    "The Validation Data": "Validation Data",
    "The Test Data": "Test Data",
    "The Overfitting": "Overfitting",
    "The Underfitting": "Underfitting",
    "The Bias": "Bias",
    "The Variance": "Variance",
    "The Accuracy": "Accuracy",
    "The Precision": "Precision",
    "The Recall": "Recall",
    "The F1 Score": "F1 Score",
    "The Confusion Matrix": "Confusion Matrix",
    "The ROC Curve": "ROC Curve",
    "The AUC": "AUC",
    "The Loss Function": "Loss Function",
    "The Cost Function": "Cost Function",
    "The Gradient Descent": "Gradient Descent",
    "The Backpropagation": "Backpropagation",
    "The Neural Network": "Neural Network",
    "The Deep Learning": "Deep Learning",
    "The Machine Learning": "Machine Learning",
    "The Reinforcement Learning": "Reinforcement Learning",
    "The Supervised Learning": "Supervised Learning",
    "The Unsupervised Learning": "Unsupervised Learning",
    "The Semi-Supervised Learning": "Semi-Supervised Learning",
    "The Self-Supervised Learning": "Self-Supervised Learning",
    lesson titles. The map is too large.

This is a bad approach. I should not write a giant mapping. Instead, I can just simplify the English titles by removing prefixes and extracting letters. For the other languages, I can keep the existing translations and just remove corresponding words heuristically. But the map is unnecessary.

Let me simplify the script. I'll use a small set of mappings and a few simple regex rules. The user just wants brief names, not perfect translations.

Actually, I think the best approach is to use a very small script that:
1. Removes "My", "The", "In the", "and ..." from English titles
2. For letter lessons, extracts the letter part
3. Keeps Arabic as is (it's already simple)
4. For other languages, apply simple heuristics: remove "Saya", "Aku", "Dan ...", "Les", "Los", etc.

Let me write that.

